//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 23:10:25  on 9 Февраль 2003 г.
//
//	Generated for file: C:\Work\Palm\Old\NREditor\Project\Rsc\NREditor.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"NR Editor"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainUnnamed1004Label                      1004	//(Left Origin = 65, Top Origin = 17, Usable = 1, Font = Standard)
#define MainPen1PushButton                        1001	//(Left Origin = 114, Top Origin = 17, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainPen3PushButton                        1002	//(Left Origin = 130, Top Origin = 17, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainPen5PushButton                        1003	//(Left Origin = 146, Top Origin = 17, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainWaterPushButton                       1005	//(Left Origin = 1, Top Origin = 34, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainGrassPushButton                       1006	//(Left Origin = 1, Top Origin = 50, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainSandPushButton                        1007	//(Left Origin = 1, Top Origin = 66, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainRoadPushButton                        1008	//(Left Origin = 1, Top Origin = 104, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainClearPushButton                       1009	//(Left Origin = 1, Top Origin = 120, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainBlockPushButton                       1010	//(Left Origin = 1, Top Origin = 82, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainWayPushButton                         1011	//(Left Origin = 1, Top Origin = 143, Width = 30, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainGroupID                               1
#define MainGroupID2                              2

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 42, Top Origin = 115, Width = 70, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define AboutUnnamed1104BitMap                    1000	//(Left Origin = 47, Top Origin = 52, Bitmap Resource ID = 1000, Usable = 1)
#define AboutUnnamed1101Label                     1101	//(Left Origin = 4, Top Origin = 143, Usable = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 39, Top Origin = 20, Usable = 1, Font = Large)
#define AboutDateLabel                            1111	//(Left Origin = 102, Top Origin = 143, Usable = 1, Font = Standard)

//	Resource: tFRM 1200
#define ManagerForm                               1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ManagerOpenButton                         1202	//(Left Origin = 102, Top Origin = 103, Width = 55, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Standard)
#define ManagerEraseButton                        1203	//(Left Origin = 102, Top Origin = 123, Width = 55, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Standard)
#define ManagerDuplicateButton                    1204	//(Left Origin = 102, Top Origin = 143, Width = 55, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Standard)
#define ManagerCreateButton                       1205	//(Left Origin = 102, Top Origin = 83, Width = 55, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Standard)
#define ManagerSafeModeCheckbox                   1207	//(Left Origin = 95, Top Origin = 1, Width = 65, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define ManagerNameLabel                          1206	//(Left Origin = 4, Top Origin = 17, Usable = 1, Font = Bold 12)
#define ManagerTracksList                         1201	//(Left Origin = 5, Top Origin = 36, Width = 90, Usable = 1, Font = Standard, Visible Items = 11)

//	Resource: tFRM 1300
#define TrackNameForm                             1300	//(Left Origin = 5, Top Origin = 50, Width = 150, Height = 55, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define TrackNameOkButton                         1302	//(Left Origin = 44, Top Origin = 37, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define TrackNameCancelButton                     1303	//(Left Origin = 99, Top Origin = 37, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define TrackNameTextField                        1301	//(Left Origin = 6, Top Origin = 18, Width = 140, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 40, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define TrackNameUnnamed1304GraffitiShift         1304	//(Left Origin = 9, Top Origin = 39)

//	Resource: tFRM 1400
#define WayForm                                   1400	//(Left Origin = 10, Top Origin = 55, Width = 140, Height = 70, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1100, Menu Bar ID = 0, Default Button ID = 0)
#define WayResetButton                            1401	//(Left Origin = 73, Top Origin = 18, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WayDoneButton                             1402	//(Left Origin = 13, Top Origin = 52, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WayCancelButton                           1403	//(Left Origin = 73, Top Origin = 52, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WayDrawRoadButton                         1405	//(Left Origin = 13, Top Origin = 34, Width = 110, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define WayHideCheckbox                           1404	//(Left Origin = 13, Top Origin = 18, Width = 55, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define NeedMoreColorsAlert                       1000
#define NeedMoreColorsExit                        0

//	Resource: Talt 1100
#define NoneTrackAlert                            1100
#define NoneTrackOK                               0

//	Resource: Talt 1200
#define SubmitEraseAlert                          1200
#define SubmitEraseOK                             0
#define SubmitEraseNo                             1

//	Resource: Talt 1300
#define LANGAlert                                 1300
#define LANG_ENG                                  0

//	Resource: Talt 1400
#define RuntimeErrorAlert                         1400
#define RuntimeErrorCloseApplication              0


//	Resource: MBAR 1000
#define NREditorMainMenuBar                       1000


//	Resource: MENU 1000
#define TrackMenu                                 1000
#define TrackManager                              1000
#define TrackClearAll                             1001
#define TrackUndoAll                              1002

//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpUseoftheEditor                        1100
#define HelpAbout                                 1101


//	Resource: tSTR 1100
#define WayPointsString                           1100	// "Points of a way is put down CONSISTENTLY. I.e. the new put point of a way will go after last. "draw a road " - draws on a way a road of CHOSEN WIDTH OF PEN."

//	Resource: tSTR 1000
#define UseEditorString                           1000	// "The track consists of 2 layers on which it is possible to draw:  	 1. A surface (grass, water, sand and barriers)  	 2. Road. The kind of a road depends on a surface, on which i"


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018

//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000

//	Resource: PICT 1009
#define BitmapID1009Bitmap                        1009

//	Resource: PICT 1010
#define BitmapID1010Bitmap                        1010


//	Resource: tbmf 1000
#define LogoBitmapFamily                          1000


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

