//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 20:40:15  on 11 Äåêàáðü 2002 ã.
//
//	Generated for file: C:\Work\Palm\NR Editor\Rsc\Graphics.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: Talt 5000
#define COLORAlert                                5000
#define COLOR_8                                   0

